Send email to Dev Support team when back-up steps fail

diff --git a/drupal_backup b/drupal_backup
--- a/drupal_backup
+++ b/drupal_backup
@@ -13,6 +13,11 @@ if [ "`/usr/bin/id -urn`" != "$USER" ] ; then
   exit 1
 fi
 
+# For sending error message emails
+SUBJECT="BACKUP ERROR Main Library Website"
+SENDER="druadmin@library.ucla.edu"
+RECIPIENTS="sgurnick@library.ucla.edu avuong@library.ucla.edu cchen@library.ucla.edu"
+
 DRUSH="/home/druadmin/.composer/vendor/bin/drush"
 
 # Get local drush alias
@@ -20,8 +25,9 @@ DRUSH="/home/druadmin/.composer/vendor/bin/drush"
 # All drush aliases can be found in ~/$USER/.drush/aliases.drushrc.php
 # Our convention for Drush aliases: @rhel-[test|stage|prod][0-9]
 SRC_DRUSH=`$DRUSH site-alias --local-only`
-if [ $? -ne 0 ] ; then
-  echo -e "Failed to get alias for local Drupal instance - exiting \n"
+if [ $? -ne 0 ] || [ -z "$SRC_DRUSH" ] ; then
+  echo "Unable to get alias for local Drupal instance - backup failed" | \
+    mailx -s "$SUBJECT" -r "$SENDER" "$RECIPIENTS"
   exit 1
 fi
 
@@ -43,7 +49,8 @@ mkdir -p $BACKUP_DIR
 echo -e "\nCreating SQL dump file from $SRC_DRUSH Drupal instance \n"
 $DRUSH $SRC_DRUSH sql-dump --result-file=$SQL_DUMP --gzip
 if [ ! -s "${SQL_DUMP}.gz" ] ; then
-  echo -e "\nFailed to create the MySQL database dump file $SQL_DUMP - exiting \n"
+  echo "Unable to create the MySQL database dump file $SQL_DUMP - backup failed" | \
+    mailx -s "$SUBJECT" -r "$SENDER" "$RECIPIENTS"
   exit 1
 fi
 
@@ -75,7 +82,8 @@ for SUBDIR in $SUBDIR_LIST; do
   # Exit codes 0 (sucess) and 1 (file changed) are acceptable - anything else is fatal error
   # Exit code 1: Periodically Varnish cache runs status.php, which adds and deletes a file in sites_default_files
   if [ $? -ne 0 -a $? -ne 1 ] ; then
-    echo -e "\nFailed to create the '$SUBDIR_TAR_GZ' archive - exiting \n"
+    echo "Unable to create the '$SUBDIR_TAR_GZ' archive - backup failed" | \
+      mailx -s "$SUBJECT" -r "$SENDER" "$RECIPIENTS"
     exit 1
   fi
 done
