Updates to support drush 7, syntax, formatting

diff --git a/drupal_backup b/drupal_backup
--- a/drupal_backup
+++ b/drupal_backup
@@ -9,20 +9,20 @@
 # Must be this user to run this script
 USER=druadmin
 if [ "`/usr/bin/id -urn`" != "$USER" ] ; then
-        echo "You must be the $USER user to execute this script - exiting."
-        exit 1
+  echo "You must be the $USER user to execute this script - exiting."
+  exit 1
 fi
 
-DRUSH=/usr/local/bin/drush
+DRUSH="/home/druadmin/.composer/vendor/bin/drush"
 
 # Get local drush alias
 # Drush Alias - only need one as all webheads share the same database instance and the same static files
 # All drush aliases can be found in ~/$USER/.drush/aliases.drushrc.php
 # Our convention for Drush aliases: @rhel-[test|stage|prod][0-9]
-SRC_DRUSH=@`$DRUSH site-alias --local`
+SRC_DRUSH=`$DRUSH site-alias --local-only`
 if [ $? -ne 0 ] ; then
-        echo -e "Failed to get alias for local Drupal instance - exiting \n"
-        exit 1
+  echo -e "Failed to get alias for local Drupal instance - exiting \n"
+  exit 1
 fi
 
 TODAY=`date +%Y%m%d`
@@ -65,7 +65,7 @@ for SUBDIR in $SUBDIR_LIST; do
   #   OS-X-specific .TemporaryItems directories
   #   Windows-specific Thumbs.db files
   # ./.check_mount, which Nagios uses to verify that the file system is mounted
-  tar czf $SUBDIR_TAR_GZ -C $WEBHEAD_ROOT/$SUBDIR .	\
+  tar czf $SUBDIR_TAR_GZ -C $WEBHEAD_ROOT/$SUBDIR .    \
     --exclude ".apdisk"           \
     --exclude ".DS_Store"         \
     --exclude ".TemporaryItems"   \
@@ -91,9 +91,9 @@ BACKUP_DATES=`find $BACKUP_TOPLEVEL -type d -name "[0-9]*" -printf "%f\n" | sort
 # Each backup directory is named in YYYYMMDD format based on the day it was created.
 # If a directory's name is older than seven days ago, the directory is removed.
 if [ -n "$BACKUP_DATES" ] ; then
-        for DATE in $BACKUP_DATES ; do
-                if [ $(( $DATE - $SEVENDAYSAGO )) -lt 0 ] ; then
-                        rm -rf $BACKUP_TOPLEVEL/$DATE
-                fi
-        done
+  for DATE in $BACKUP_DATES ; do
+    if [ $(( $DATE - $SEVENDAYSAGO )) -lt 0 ] ; then
+      rm -rf $BACKUP_TOPLEVEL/$DATE
+    fi
+  done
 fi
diff --git a/drupal_copy_code b/drupal_copy_code
--- a/drupal_copy_code
+++ b/drupal_copy_code
@@ -14,24 +14,24 @@
 #   an entry for the local machine
 USER=druadmin
 if [ "`/usr/bin/id -urn`" != "$USER" ] ; then
-	echo "You must be the $USER user to execute this script - exiting."
-	exit 1
+  echo "You must be the $USER user to execute this script - exiting."
+  exit 1
 fi
 
 # Avoid being in the Drupal root tree to avoid built-in aliases (e.g. @self)
 cd $HOME
 
-DRUSH="/usr/local/bin/drush"
+DRUSH="/home/druadmin/.composer/vendor/bin/drush"
 
 # STEP 1 ---------------------------------------------------------------------------------------------------------------------------
 echo -e "\nSTEP 1"
 
 # Get local drush alias
 # All drush aliases can be found in /home/$USER/.drush/aliases.drushrc.php
-SRC_ALIAS=`$DRUSH site-alias --local`
+SRC_ALIAS=`$DRUSH site-alias --local-only`
 if [ $? -ne 0 ] ; then
-	echo -e "\nUnable to get source alias for local Drupal instance - exiting."
-	exit 1
+  echo -e "\nUnable to get source alias for local Drupal instance - exiting."
+  exit 1
 fi
 
 # Expected drush alias format is rhel-test[digits], rhel-stage[digits], rhel-prod[digits]
@@ -41,38 +41,38 @@ echo -e "\nCollecting variables from all $BASE_ALIAS Drupal instances."
 # Get drush aliases for fellow sites
 DEST_ALIASES=`$DRUSH site-alias | grep -v $SRC_ALIAS | grep $BASE_ALIAS`
 if [ -z "$DEST_ALIASES" ] ; then
-	echo -e "\nUnable to get destination aliases - exiting."
-	exit 1
+  echo -e "\nUnable to get destination aliases - exiting."
+  exit 1
 fi
 
 # Get URIS for local and fellow sites
-SRC_URI="`$DRUSH site-alias --field-labels=0 --fields=uri --format=list @$SRC_ALIAS`"
+SRC_URI="`$DRUSH site-alias --field-labels=0 --fields=uri --format=list $SRC_ALIAS`"
 if [ -z "$SRC_URI" ] ; then
-	echo -e "\nNo source webheads found - exiting."
-	exit 1
+  echo -e "\nNo source webheads found - exiting."
+  exit 1
 fi
 DEST_URIS=""
 for ALIAS in $DEST_ALIASES ; do
-        DEST_URIS="$DEST_URIS `$DRUSH site-alias --field-labels=0 --fields=uri --format=list @$ALIAS`"
+        DEST_URIS="$DEST_URIS `$DRUSH site-alias --field-labels=0 --fields=uri --format=list $ALIAS`"
 done
 if [ -z "$DEST_URIS" ] ; then
-	echo -e "\nNo destination webheads found - exiting."
-	exit 1
+  echo -e "\nNo destination webheads found - exiting."
+  exit 1
 fi
 
 # Determine Drupal Code directory: it is the same on source and all destinations
 
 # Ask source for its Drupal root directory
-SRC_ROOT_DIR=`$DRUSH site-alias --field-labels=0 --fields=root --format=list @$SRC_ALIAS 2>/dev/null`
+SRC_ROOT_DIR=`$DRUSH site-alias --field-labels=0 --fields=root --format=list $SRC_ALIAS 2>/dev/null`
 if [ $? -ne 0 ] ; then
-        echo -e "\nUnable to determine $SRC_ALIAS root directory - exiting."
-        exit 1
+  echo -e "\nUnable to determine $SRC_ALIAS root directory - exiting."
+  exit 1
 fi
 # Drupal code directory is one level above
 DRUPAL_CODE_DIR=`dirname $SRC_ROOT_DIR 2>/dev/null`
 if [ $? -ne 0 ] ; then
-        echo -e "\nUnable to determine $SRC_ALIAS code directory - exiting."
-        exit 1
+  echo -e "\nUnable to determine $SRC_ALIAS code directory - exiting."
+  exit 1
 fi
 
 echo -e "\nSucessfully connected to $SRC_ALIAS and $DEST_ALIASES Drupal instances."
@@ -82,7 +82,7 @@ echo -e "\n\nSTEP 2"
 
 # Put local Drupal instance into maintenance (read-only) mode
 echo -e "\nPutting the $SRC_ALIAS Drupal instance into maintenance mode."
-$DRUSH @$SRC_ALIAS vset maintenance_mode 1
+$DRUSH $SRC_ALIAS vset maintenance_mode 1
 
 # STEP 3 ---------------------------------------------------------------------------------------------------------------------------
 echo -e "\n\nSTEP 3"
@@ -106,10 +106,10 @@ echo -e "\n\nSTEP 3"
 # Appending a slash to the source directory name causes rsync to copy the contents
 # Otherwise, rsync would copy the directory itself
 for DEST_URI in $DEST_URIS; do
-        echo -e "\nCopying Drupal code files from here to $DEST_URI."
-        rsync -e 'ssh' -c -r -l -g -o -p -t -H -v	\
-		--delete --safe-links --temp-dir=/tmp	\
-		$DRUPAL_CODE_DIR/ $DEST_URI:$DRUPAL_CODE_DIR
+  echo -e "\nCopying Drupal code files from here to $DEST_URI."
+  rsync -e 'ssh' -c -r -l -g -o -p -t -H -v	\
+    --delete --safe-links --temp-dir=/tmp	\
+    $DRUPAL_CODE_DIR/ $DEST_URI:$DRUPAL_CODE_DIR
 done
 
 # STEP 4 ---------------------------------------------------------------------------------------------------------------------------
@@ -117,20 +117,19 @@ echo -e "\n\nSTEP 4"
 
 # Apply any database changes.
 echo -e "\nApplying any database changes."
-$DRUSH @$SRC_ALIAS -y updatedb
+$DRUSH $SRC_ALIAS -y updatedb
 
 # Clear the cache
 echo -e "\nClearing the Drupal cache."
-$DRUSH @$SRC_ALIAS -y cache-clear all
+$DRUSH $SRC_ALIAS -y cache-clear all
 
 # Turn maintenance mode off
 echo -e "\nTurning maintenance mode off."
-$DRUSH @$SRC_ALIAS vset maintenance_mode 0
+$DRUSH $SRC_ALIAS vset maintenance_mode 0
 
 # Clear the cache again to be sure maintenance mode is not preserved
 echo -e "\nClearing the Drupal cache."
-$DRUSH @$SRC_ALIAS -y cache-clear all
+$DRUSH $SRC_ALIAS -y cache-clear all
 
 # All done
 echo -e "\nCopying of code from here to$DEST_URIS is complete."
-
diff --git a/drupal_get_prod_content b/drupal_get_prod_content
--- a/drupal_get_prod_content
+++ b/drupal_get_prod_content
@@ -20,14 +20,14 @@
 #   an entry for the local machine
 USER=druadmin
 if [ "`/usr/bin/id -urn`" != "$USER" ] ; then
-	echo "You must be the $USER user to execute this script - exiting."
-	exit 1
+  echo "You must be the $USER user to execute this script - exiting."
+  exit 1
 fi
 
 # Avoid being in the Drupal root tree to avoid built-in aliases (e.g. @self)
 cd $HOME
 
-DRUSH="/usr/local/bin/drush"
+DRUSH="/home/druadmin/.composer/vendor/bin/drush"
 
 # Can this value be found somewhere, instead of being hard-coded?
 # Webhead Static Files Dir - path is the same on all Webheads
@@ -35,23 +35,23 @@ STATIC_FILES="/var/www/vhosts/webhead/sites_default_files/"
 
 # Get local (destination) drush alias
 # All drush aliases can be found in /home/$USER/.drush/aliases.drushrc.php
-DEST_ALIAS=`$DRUSH site-alias --local`
+DEST_ALIAS=`$DRUSH site-alias --local-only`
 if [ $? -ne 0 ] ; then
-        echo -e "Unable to get destination alias for local Drupal instance - exiting \n"
-        exit 1
+  echo -e "Unable to get destination alias for local Drupal instance - exiting \n"
+  exit 1
 fi
 
 # Ensure that (local) destination is RHEL test or stage
 # Expected drush alias format is rhel-test[digits], rhel-stage[digits], rhel-prod[digits]
 case "$DEST_ALIAS" in
-rhel-test*|rhel-stage*)
-	# Database content will be copied from production to $DEST_ALIAS
-	SRC_ALIAS="rhel-prod1"
-	;;
+@rhel-test*|@rhel-stage*)
+  # Database content will be copied from production to $DEST_ALIAS
+  SRC_ALIAS="@rhel-prod1"
+  ;;
 *)
-	echo -e" Must run this script on RHEL test or stage - exiting \n"
-	exit 1
-	;;
+  echo "Must run this script on RHEL test or stage - exiting"
+  exit 1
+  ;;
 esac
 
 # STEP 1 --------------------------------------------------------------------------------------------------------------
@@ -59,10 +59,10 @@ echo -e "\nSTEP 1 \n"
 
 # Get $SRC_ALIAS hostname, and test ability of drush command to access $SRC_ALIAS
 echo -e "Testing ability to reach $SRC_ALIAS....\n"
-SRC_URI=`$DRUSH site-alias --field-labels=0 --fields=uri --format=list @$SRC_ALIAS`
+SRC_URI=`$DRUSH site-alias --field-labels=0 --fields=uri --format=list $SRC_ALIAS`
 if [ $? -gt 0 ] ; then
-	echo -e "Unable to reference $SRC_ALIAS - exiting \n"
-	exit 1
+  echo -e "Unable to reference $SRC_ALIAS - exiting \n"
+  exit 1
 fi
 echo -e "Sucessfully connected to $SRC_ALIAS instance. \n"
 
@@ -85,11 +85,12 @@ echo -e "\nSTEP 2 \n"
 # --safe-links = ignore symlinks that point outside the tree (but there aren't any)
 
 for DIR in $STATIC_FILES; do
-    echo -e "Copying $DIR used by $SRC_ALIAS to the one used by $DEST_ALIAS ... \n"
-    sudo -u root /usr/bin/rsync -e 'ssh' -r -l -o -g -t -H -p -v \
-	--delete --safe-links \
-	--log-format="%o %b %f%L" \
-	$USER@$SRC_URI:$DIR $DIR
+  echo -e "Copying $DIR used by $SRC_ALIAS to the one used by $DEST_ALIAS ... \n"
+  sudo -u root /usr/bin/rsync -e 'ssh' -r -l -o -g -t -H -p -v \
+    --delete --safe-links \
+    --exclude='.snapshot' \
+    --log-format="%o %b %f%L" \
+    $USER@$SRC_URI:$DIR $DIR
 done
 
 # STEP 3 --------------------------------------------------------------------------------------------------------------
@@ -97,21 +98,21 @@ echo -e "\nSTEP 3 \n"
 
 # Drop all tables in the database used by $DEST_ALIAS - this is to ensure a clean local environment
 echo -e "Dropping all tables used by $DEST_ALIAS. \n"
-$DRUSH @$DEST_ALIAS sql-drop --yes
+$DRUSH $DEST_ALIAS sql-drop --yes
 
 # STEP 4 --------------------------------------------------------------------------------------------------------------
 echo -e "\nSTEP 4 \n"
 
 # Copy the database used by $SRC_ALIAS to the one used by $DEST_ALIAS
 echo -e "Copying the database used by $SRC_ALIAS to the one used by $DEST_ALIAS. \n"
-$DRUSH sql-sync @$SRC_ALIAS @$DEST_ALIAS --no-cache --yes
+$DRUSH sql-sync $SRC_ALIAS $DEST_ALIAS --yes
 
 # STEP 5 --------------------------------------------------------------------------------------------------------------
 echo -e "\nSTEP 5 \n"
 
 # Clear the $DEST_ALIAS Drupal Cache
 echo -e "Clearing the Drupal cache for $DEST_ALIAS... \n"
-$DRUSH @$DEST_ALIAS cache-clear all
+$DRUSH $DEST_ALIAS cache-clear all
 
 # Drupal refresh is complete
 echo -e "Drupal content copy from $SRC_ALIAS to $DEST_ALIAS is complete. \n"
